import { create } from "zustand"
import type { VideoClientState } from "../types/type"

export const videoauthstore = create<VideoClientState>((set) => ({
    provider: "",
    model: "",
    videoSrc: null,
    videoFile: null,
    summary: null,
    timestamps: [],
    loadingupload: false,
    analysisError: false,
    modelList: [],
    modelsLoading: false,
    modelOpen: false,
    Api: [],
    isPending: false,
    setsummary: (summary) => set({ summary }),
    settimestamps: (timestamps) => set({ timestamps }),
    setVideoSrc: (videoSrc) => set({ videoSrc }),
    setVideoFile: (videoFile) => set({ videoFile }),
    setProvider: (provider) => set({ provider, model: "" }),
    setModel: (model) => set({ model }),
    setloadingupload: (loadingupload) => set({ loadingupload }),
    setanalysisError: (analysisError) => set({ analysisError }),
    setmodelList: (modelList) => set({ modelList }),
    setmodelsLoading: (modelsLoading) => set({ modelsLoading }),
    setmodelOpen: (modelOpen) => set({ modelOpen }),
    setApi: (Api) => set({ Api }),
    setisPending: (isPending) => set({ isPending }),
    generateTranscript: null,
    handleClearVideo: null,
    handleContainerClick: null,
    registerHandlers: (handlers) => set({
        generateTranscript: handlers.generateTranscript,
        handleClearVideo: handlers.handleClearVideo,
        handleContainerClick: handlers.handleContainerClick,
    }),
}))
