import { create } from "zustand";
import type { GoogleClientState, sheetcrondata, docscrondata } from "../types/type";

export const initialSheetCron: sheetcrondata = {
  isActive: false,
  sheetUrl: "",
  sheetName: "",
  model: "",
  provider: "",
  message: "",
  crontype: "minute",
  triggerAt: "09:00",
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC",
  customSchedule: "",
};

export const initialDocsCron: docscrondata = {
  isActive: false,
  docsUrl: "",
  docsName: "",
  model: "",
  provider: "",
  message: "",
  crontype: "minute",
  triggerAt: "09:00",
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC",
  customSchedule: "",
};

export const googleauthstore = create<GoogleClientState>((set) => ({
  provider: "",
  model: "",
  sheeturl: "",
  docsurl: "",

  // Docs initial
  sessionmessage_docs: [],
  input_docs: "",
  sending_docs: false,
  loadingfetch_docs: false,
  loadingerror_docs: false,
  nextCursor_docs: null,
  hasMore_docs: false,
  loadingMore_docs: false,
  type_docs: "text",
  opendocs: false,
  docsinput: "",
  lightboxImages_docs: [],
  lightboxIndex_docs: 0,
  lightboxOpen_docs: false,
  copiedIndex_docs: null,
  uploadingImages_docs: false,
  uploadingImageUrls_docs: new Set(),
  pendingImages_docs: [],
  modelList_docs: [],
  modelsLoading_docs: false,
  reasoningLevel_docs: "",
  recordstatus_docs: false,
  loadingrecord_docs: false,
  pendingApproval: null,
  pendingApprovalRef: { current: null },
  threadIdRef: { current: null },

  // Sheet initial
  sessionmessage_sheet: [],
  input_sheet: "",
  sending_sheet: false,
  loadingfetch_sheet: false,
  loadingerror_sheet: false,
  nextCursor_sheet: null,
  hasMore_sheet: false,
  loadingMore_sheet: false,
  type_sheet: "text",
  hover_sheet: false,
  opensheet: false,
  sheetinput: "",
  pendingApproval_sheet: null,
  pendingApprovalRef_sheet: { current: null },
  threadIdRef_sheet: { current: null },
  lightboxImages_sheet: [],
  lightboxIndex_sheet: 0,
  lightboxOpen_sheet: false,
  copiedIndex_sheet: null,
  uploadingImages_sheet: false,
  uploadingImageUrls_sheet: new Set(),
  pendingImages_sheet: [],
  modelList_sheet: [],
  modelsLoading_sheet: false,
  reasoningLevel_sheet: "",
  recordstatus_sheet: false,
  loadingrecord_sheet: false,

  opensheetcron: false,
  loadingsheetcroncreate: false,
  sheetcron: { ...initialSheetCron },
  customDayOfWeek_sheet: [],
  customDayOfMonth_sheet: [],
  customMonth_sheet: [],

  opendocscron: false,
  loadingdocscroncreate: false,
  doccron: { ...initialDocsCron },
  customDayOfWeek_docs: [],
  customDayOfMonth_docs: [],
  customMonth_docs: [],

  // Shared setters
  setsheeturl: (sheeturl) => set({ sheeturl }),
  setdocsurl: (docsurl) => set({ docsurl }),
  setProvider: (provider) => set({ provider, model: "" }),
  setModel: (model) => set({ model }),
  resetgoogle: () => set({ provider: "", model: "", sheeturl: "", docsurl: "" }),

  // Docs setters
  setsessionmessage_docs: (v) => set({ sessionmessage_docs: v }),
  setInput_docs: (v) => set({ input_docs: v }),
  setSending_docs: (v) => set({ sending_docs: v }),
  setloadingfetch_docs: (v) => set({ loadingfetch_docs: v }),
  setloadingerror_docs: (v) => set({ loadingerror_docs: v }),
  setNextCursor_docs: (v) => set({ nextCursor_docs: v }),
  setHasMore_docs: (v) => set({ hasMore_docs: v }),
  setLoadingMore_docs: (v) => set({ loadingMore_docs: v }),
  settype_docs: (v) => set({ type_docs: v }),
  setOpendocs: (v) => set({ opendocs: v }),
  setDocsinput: (v) => set({ docsinput: v }),
  setLightboxImages_docs: (v) => set({ lightboxImages_docs: v }),
  setLightboxIndex_docs: (v) => set({ lightboxIndex_docs: v }),
  setLightboxOpen_docs: (v) => set({ lightboxOpen_docs: v }),
  setCopiedIndex_docs: (v) => set({ copiedIndex_docs: v }),
  setUploadingImages_docs: (v) => set({ uploadingImages_docs: v }),
  setUploadingImageUrls_docs: (v) => set({ uploadingImageUrls_docs: v }),
  setPendingImages_docs: (v) => set({ pendingImages_docs: v }),
  setModelList_docs: (v) => set({ modelList_docs: v }),
  setModelsLoading_docs: (v) => set({ modelsLoading_docs: v }),
  setReasoningLevel_docs: (v) => set({ reasoningLevel_docs: v }),
  setRecordstatus_docs: (v) => set({ recordstatus_docs: v }),
  setLoadingrecord_docs: (v) => set({ loadingrecord_docs: v }),
  setPendingApproval: (v) => set({ pendingApproval: v }),
  updateSessionMessages_docs: (updater) =>
    set((state) => ({ sessionmessage_docs: updater(state.sessionmessage_docs) })),

  // Sheet setters
  setsessionmessage_sheet: (v) => set({ sessionmessage_sheet: v }),
  setInput_sheet: (v) => set({ input_sheet: v }),
  setSending_sheet: (v) => set({ sending_sheet: v }),
  setloadingfetch_sheet: (v) => set({ loadingfetch_sheet: v }),
  setloadingerror_sheet: (v) => set({ loadingerror_sheet: v }),
  setNextCursor_sheet: (v) => set({ nextCursor_sheet: v }),
  setHasMore_sheet: (v) => set({ hasMore_sheet: v }),
  setLoadingMore_sheet: (v) => set({ loadingMore_sheet: v }),
  settype_sheet: (v) => set({ type_sheet: v }),
  setHover_sheet: (v) => set({ hover_sheet: v }),
  setOpensheet: (v) => set({ opensheet: v }),
  setsheetinput: (v) => set({ sheetinput: v }),
  setPendingApproval_sheet: (v) => set({ pendingApproval_sheet: v }),
  setLightboxImages_sheet: (v) => set({ lightboxImages_sheet: v }),
  setLightboxIndex_sheet: (v) => set({ lightboxIndex_sheet: v }),
  setLightboxOpen_sheet: (v) => set({ lightboxOpen_sheet: v }),
  setCopiedIndex_sheet: (v) => set({ copiedIndex_sheet: v }),
  setUploadingImages_sheet: (v) => set({ uploadingImages_sheet: v }),
  setUploadingImageUrls_sheet: (v) => set({ uploadingImageUrls_sheet: v }),
  setPendingImages_sheet: (v) => set({ pendingImages_sheet: v }),
  setModelList_sheet: (v) => set({ modelList_sheet: v }),
  setModelsLoading_sheet: (v) => set({ modelsLoading_sheet: v }),
  setReasoningLevel_sheet: (v) => set({ reasoningLevel_sheet: v }),
  setrecordstatus_sheet: (v) => set({ recordstatus_sheet: v }),
  setloadingrecord_sheet: (v) => set({ loadingrecord_sheet: v }),
  updateSessionMessages_sheet: (updater) =>
    set((state) => ({ sessionmessage_sheet: updater(state.sessionmessage_sheet) })),

  setOpensheetcron: (v) => set({ opensheetcron: v }),
  setLoadingsheetcroncreate: (v) => set({ loadingsheetcroncreate: v }),
  setSheetcron: (v) => set({ sheetcron: v }),
  setCustomDayOfWeek_sheet: (v) => set({ customDayOfWeek_sheet: v }),
  setCustomDayOfMonth_sheet: (v) => set({ customDayOfMonth_sheet: v }),
  setCustomMonth_sheet: (v) => set({ customMonth_sheet: v }),

  setOpendocscron: (v) => set({ opendocscron: v }),
  setLoadingdocscroncreate: (v) => set({ loadingdocscroncreate: v }),
  setDoccron: (v) => set({ doccron: v }),
  setCustomDayOfWeek_docs: (v) => set({ customDayOfWeek_docs: v }),
  setCustomDayOfMonth_docs: (v) => set({ customDayOfMonth_docs: v }),
  setCustomMonth_docs: (v) => set({ customMonth_docs: v }),
}));
