import { create } from "zustand";
import type { AccountState } from "../types/type";

export const accountstore = create<AccountState>((set) => ({
  username: "",
  currentpassword: "",
  newpassword: "",
  code: "",
  openverify: false,
  stateid: "",
  timer: 0,
  preview: null,
  loadingupdate: false,
  loadingpassword: false,
  loadingpasswordverify: false,
  loadingpasswordresend: false,
  loadingpasswordchange: false,
  dialogService: null,
  search: "",
  deleteDialogOpen: false,
  deleteloading: false,

  setUsername: (v) => set({ username: v }),
  setCurrentpassword: (v) => set({ currentpassword: v }),
  setNewpassword: (v) => set({ newpassword: v }),
  setCode: (v) => set({ code: v }),
  setOpenverify: (v) => set({ openverify: v }),
  setStateid: (v) => set({ stateid: v }),
  setTimer: (v) => set({ timer: v }),
  setPreview: (v) => set({ preview: v }),
  setLoadingupdate: (v) => set({ loadingupdate: v }),
  setLoadingpassword: (v) => set({ loadingpassword: v }),
  setLoadingpasswordverify: (v) => set({ loadingpasswordverify: v }),
  setLoadingpasswordresend: (v) => set({ loadingpasswordresend: v }),
  setLoadingpasswordchange: (v) => set({ loadingpasswordchange: v }),
  setDialogService: (v) => set({ dialogService: v }),
  setSearch: (v) => set({ search: v }),
  setDeleteDialogOpen: (v) => set({ deleteDialogOpen: v }),
  setDeleteloading: (v) => set({ deleteloading: v }),
}));
