import { create } from "zustand";
import type { NotionClientState, notioncrondata } from "../types/type";

export const initialNotionCron: notioncrondata = {
  isActive: false,
  pageId: "",
  pageName: "",
  model: "",
  provider: "",
  message: "",
  crontype: "minute",
  triggerAt: "09:00",
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC",
  customSchedule: "",
};

export const notionauthstore = create<NotionClientState>((set) => ({
  provider: "",
  model: "",
  sessionmessage: [],
  input: "",
  sending: false,
  loadingfetch: false,
  loadingerror: false,
  loadingnotionmsg: false,
  nextCursor: null,
  hasMore: false,
  loadingMore: false,
  type: "text",
  pageid: null,
  isChecking: false,
  pendingApproval: null,
  pendingApprovalRef: { current: null },
  threadIdRef: { current: null },
  lightboxImages: [],
  lightboxIndex: 0,
  lightboxOpen: false,
  copiedIndex: null,
  uploadingImages: false,
  uploadingImageUrls: new Set(),
  pendingImages: [],
  modelList: [],
  modelsLoading: false,
  reasoningLevel: "",
  opencron: false,
  loadingcroncreate: false,
  notioncron: { ...initialNotionCron },
  customDayOfWeek: [],
  customDayOfMonth: [],
  customMonth: [],

  setProvider: (v) => set({ provider: v, model: "" }),
  setModel: (v) => set({ model: v }),
  setsessionmessage: (v) => set({ sessionmessage: v }),
  setInput: (v) => set({ input: v }),
  setSending: (v) => set({ sending: v }),
  setloadingfetch: (v) => set({ loadingfetch: v }),
  setloadingerror: (v) => set({ loadingerror: v }),
  setloadingnotionmsg: (v) => set({ loadingnotionmsg: v }),
  setNextCursor: (v) => set({ nextCursor: v }),
  setHasMore: (v) => set({ hasMore: v }),
  setLoadingMore: (v) => set({ loadingMore: v }),
  settype: (v) => set({ type: v }),
  setpageid: (v) => set({ pageid: v }),
  setIsChecking: (v) => set({ isChecking: v }),
  setPendingApproval: (v) => set({ pendingApproval: v }),
  setLightboxImages: (v) => set({ lightboxImages: v }),
  setLightboxIndex: (v) => set({ lightboxIndex: v }),
  setLightboxOpen: (v) => set({ lightboxOpen: v }),
  setCopiedIndex: (v) => set({ copiedIndex: v }),
  setUploadingImages: (v) => set({ uploadingImages: v }),
  setUploadingImageUrls: (v) => set({ uploadingImageUrls: v }),
  setPendingImages: (v) => set({ pendingImages: v }),
  setModelList: (v) => set({ modelList: v }),
  setModelsLoading: (v) => set({ modelsLoading: v }),
  setReasoningLevel: (v) => set({ reasoningLevel: v }),
  setOpencron: (v) => set({ opencron: v }),
  setLoadingcroncreate: (v) => set({ loadingcroncreate: v }),
  setNotioncron: (v) => set({ notioncron: v }),
  setCustomDayOfWeek: (v) => set({ customDayOfWeek: v }),
  setCustomDayOfMonth: (v) => set({ customDayOfMonth: v }),
  setCustomMonth: (v) => set({ customMonth: v }),

  resetnotion: () => set({ provider: "", model: "" }),
  updateSessionMessages: (updater) =>
    set((state) => ({ sessionmessage: updater(state.sessionmessage) })),
}));
