import { create } from "zustand";
import type { telegramcrondata, TelegramClientState } from "@/features/telegram/types/type";

const initialTelegramCron: telegramcrondata = {
  isActive: false,
  channel: "",
  chatId: "",
  model: "",
  provider: "",
  message: "",
  crontype: "",
  triggerAt: "",
  timezone: "",
  customSchedule: "",
};

export const telegramauthstore = create<TelegramClientState>((set) => ({
  provider: "",
  model: "",
  mode: "group",
  selectedGroupId: "",
  selectedContactId: "",
  sessionmessage: [],
  input: "",
  sending: false,
  reasoningLevel: "",
  pendingImages: [],
  uploadingImages: false,
  uploadingImageUrls: new Set(),
  loadingfetch: false,
  loadingerror: false,
  nextCursor: null,
  hasMore: false,
  loadingMore: false,
  type: "",
  hover: false,
  opencreate: false,
  openverify: false,
  opencron: false,
  phonenumber: "",
  countryCode: "+95",
  phonecode: "",
  password: "",
  loading: false,
  loadingverify: false,
  loadingdeletemsg: false,
  loadingcroncreate: false,
  pendingApproval: null,
  pendingApprovalRef: { current: null },
  threadIdRef: { current: null },
  lightboxImages: [],
  lightboxIndex: 0,
  lightboxOpen: false,
  copiedIndex: null,
  telegramcron: { ...initialTelegramCron },
  customDayOfWeek: [],
  customDayOfMonth: [],
  customMonth: [],

  setProvider: (v) => set({ provider: v, model: "" }),
  setModel: (v) => set({ model: v }),
  setmode: (v) => set({ mode: v }),
  setSelectedGroupId: (v) => set({ selectedGroupId: v }),
  setSelectedContactId: (v) => set({ selectedContactId: v }),
  setsessionmessage: (v) => set({ sessionmessage: v }),
  setInput: (v) => set({ input: v }),
  setSending: (v) => set({ sending: v }),
  setReasoningLevel: (v) => set({ reasoningLevel: v }),
  setPendingImages: (v) => set({ pendingImages: v }),
  setUploadingImages: (v) => set({ uploadingImages: v }),
  setUploadingImageUrls: (v) => set({ uploadingImageUrls: v }),
  setloadingfetch: (v) => set({ loadingfetch: v }),
  setloadingerror: (v) => set({ loadingerror: v }),
  setNextCursor: (v) => set({ nextCursor: v }),
  setHasMore: (v) => set({ hasMore: v }),
  setLoadingMore: (v) => set({ loadingMore: v }),
  settype: (v) => set({ type: v }),
  setHover: (v) => set({ hover: v }),
  setOpencreate: (v) => set({ opencreate: v }),
  setOpenverify: (v) => set({ openverify: v }),
  setOpencron: (v) => set({ opencron: v }),
  setPhonenumber: (v) => set({ phonenumber: v }),
  setCountryCode: (v) => set({ countryCode: v }),
  setPhonecode: (v) => set({ phonecode: v }),
  setPassword: (v) => set({ password: v }),
  setLoading: (v) => set({ loading: v }),
  setLoadingverify: (v) => set({ loadingverify: v }),
  setLoadingdeletemsg: (v) => set({ loadingdeletemsg: v }),
  setLoadingcroncreate: (v) => set({ loadingcroncreate: v }),
  setPendingApproval: (v) => set({ pendingApproval: v }),
  setLightboxImages: (v) => set({ lightboxImages: v }),
  setLightboxIndex: (v) => set({ lightboxIndex: v }),
  setLightboxOpen: (v) => set({ lightboxOpen: v }),
  setCopiedIndex: (v) => set({ copiedIndex: v }),
  setTelegramcron: (v) => set({ telegramcron: v }),
  setCustomDayOfWeek: (v) => set({ customDayOfWeek: v }),
  setCustomDayOfMonth: (v) => set({ customDayOfMonth: v }),
  setCustomMonth: (v) => set({ customMonth: v }),
  resettelegram: () =>
    set({ provider: "", model: "", mode: "group", selectedGroupId: "", selectedContactId: "" }),
  updateSessionMessages: (updater) =>
    set((state) => ({ sessionmessage: updater(state.sessionmessage) })),
}));
