import { create } from "zustand";
import type { ChatClientState } from "../types/type";

export const chatauthstore = create<ChatClientState>((set) => ({
  Chat: [],
  chatNextCursor: null,
  chatHasMore: false,
  chatLoadingMore: false,
  provider: "",
  model: "",
  reasoningLevel: "",
  sessionmessage: [],
  input: "",
  sending: false,
  loadingfetch: false,
  loadingerror: false,
  nextCursor: null,
  hasMore: false,
  loadingMore: false,
  type: "text",
  pendingApproval: null,
  lightboxImages: [],
  lightboxIndex: 0,
  lightboxOpen: false,
  copiedIndex: null,
  uploadingImages: false,
  uploadingImageUrls: new Set(),
  pendingImages: [],
  recordstatus: false,
  loadingrecord: false,

  pendingApprovalRef: { current: null },
  threadIdRef: { current: null },

  setChats: (Chat, chatNextCursor, chatHasMore) => set({ Chat, chatNextCursor, chatHasMore }),
  setChatNextCursor: (v) => set({ chatNextCursor: v }),
  setChatHasMore: (v) => set({ chatHasMore: v }),
  setChatLoadingMore: (v) => set({ chatLoadingMore: v }),
  resetchat: () =>
    set({
      Chat: [],
      provider: "",
      model: "",
      reasoningLevel: "",
      chatNextCursor: null,
      chatHasMore: false,
      chatLoadingMore: false,
    }),
  setProvider: (provider) => set({ provider, model: "" }),
  setModel: (model) => set({ model }),
  setReasoningLevel: (reasoningLevel) => set({ reasoningLevel }),
  setsessionmessage: (messages) => set({ sessionmessage: messages }),
  setInput: (input) => set({ input }),
  setSending: (v) => set({ sending: v }),
  setloadingfetch: (v) => set({ loadingfetch: v }),
  setloadingerror: (v) => set({ loadingerror: v }),
  setNextCursor: (v) => set({ nextCursor: v }),
  setHasMore: (v) => set({ hasMore: v }),
  setLoadingMore: (v) => set({ loadingMore: v }),
  settype: (v) => set({ type: v }),
  setPendingApproval: (v) => set({ pendingApproval: v }),
  setLightboxImages: (v) => set({ lightboxImages: v }),
  setLightboxIndex: (v) => set({ lightboxIndex: v }),
  setLightboxOpen: (v) => set({ lightboxOpen: v }),
  setCopiedIndex: (v) => set({ copiedIndex: v }),
  setUploadingImages: (v) => set({ uploadingImages: v }),
  setUploadingImageUrls: (v) => set({ uploadingImageUrls: v }),
  setPendingImages: (images) => set({ pendingImages: images }),
  setrecordstatus: (v) => set({ recordstatus: v }),
  setloadingrecord: (v) => set({ loadingrecord: v }),

  updateSessionMessages: (updater) =>
    set((state) => ({ sessionmessage: updater(state.sessionmessage) })),
}));
