import { create } from "zustand";
import type { AgentClientState } from "../types/type";

export const useagentstore = create<AgentClientState>((set, get) => ({
  type: "All",
  setType: (type) => set({ type }),
  resetagent: () => set({ type: "All" }),

  provider: "",
  model: "",
  setProvider: (provider) => set({ provider, model: "" }),
  setModel: (model) => set({ model }),

  input: "",
  setInput: (input) => set({ input }),

  selectnode: null,
  setSelectnode: (selectnode) => set({ selectnode }),
  firstnode: null,
  setFirstnode: (firstnode) => set({ firstnode }),
  lastnode: null,
  setLastnode: (lastnode) => set({ lastnode }),

  messageloading: false,
  setMessageloading: (messageloading) => set({ messageloading }),
  workflowloading: false,
  setWorkflowloading: (workflowloading) => set({ workflowloading }),
  loopIteration: { current: 0, max: 0 },
  setLoopIteration: (loopIteration) => set({ loopIteration }),

  history: [],
  setHistory: (history) => set({ history }),
  loadingfetch: false,
  setLoadingfetch: (loadingfetch) => set({ loadingfetch }),
  loadingerror: false,
  setLoadingerror: (loadingerror) => set({ loadingerror }),
  nextCursor: null,
  setNextCursor: (nextCursor) => set({ nextCursor }),
  hasMore: false,
  setHasMore: (hasMore) => set({ hasMore }),
  loadingMore: false,
  setLoadingMore: (loadingMore) => set({ loadingMore }),

  nodes: [],
  setNodes: (nodes) => set(typeof nodes === "function" ? { nodes: nodes(get().nodes) } : { nodes }),

  modelList: [],
  setModelList: (modelList) => set({ modelList }),
  modelsLoading: false,
  setModelsLoading: (modelsLoading) => set({ modelsLoading }),

  nodeDialogOpen: false,
  setNodeDialogOpen: (nodeDialogOpen) => set({ nodeDialogOpen }),
  nodeDialogMode: "create",
  setNodeDialogMode: (nodeDialogMode) => set({ nodeDialogMode }),
  nodeid: "",
  setNodeid: (nodeid) => set({ nodeid }),
  name: "",
  setName: (name) => set({ name }),
  actor: "",
  setActor: (actor) => set({ actor }),
  prompt: "",
  setPrompt: (prompt) => set({ prompt }),
  tool: null,
  setTool: (tool) => set({ tool }),
  toolOpen: false,
  setToolOpen: (toolOpen) => set({ toolOpen }),
  providerOpen: false,
  setProviderOpen: (providerOpen) => set({ providerOpen }),
  modelOpen: false,
  setModelOpen: (modelOpen) => set({ modelOpen }),

  servicesOpen: false,
  setServicesOpen: (servicesOpen) => set({ servicesOpen }),

  copiedIndex: null,
  setCopiedIndex: (copiedIndex) => set({ copiedIndex }),
  lightboxImages: [],
  setLightboxImages: (lightboxImages) => set({ lightboxImages }),
  lightboxIndex: 0,
  setLightboxIndex: (lightboxIndex) => set({ lightboxIndex }),
  lightboxOpen: false,
  setLightboxOpen: (lightboxOpen) => set({ lightboxOpen }),

  pendingImages: [],
  setPendingImages: (pendingImages) => set({ pendingImages }),
  uploadingImages: false,
  setUploadingImages: (uploadingImages) => set({ uploadingImages }),
  uploadingImageUrls: new Set(),
  setUploadingImageUrls: (uploadingImageUrls) => set({ uploadingImageUrls }),

  pendingToolApproval: null,
  setPendingToolApproval: (pendingToolApproval) => set({ pendingToolApproval }),

  topSentinelRef: { current: null },
  scrollContainerRef: { current: null },
  historyEndRef: { current: null },
  workflowGenRef: { current: 0 },
  pendingApprovalRef: { current: null },
  threadIdRef: { current: null },

  recordstatus: false,
  setRecordstatus: (recordstatus) => set({ recordstatus }),
  loadingrecord: false,
  setLoadingrecord: (loadingrecord) => set({ loadingrecord }),

  resetForm: () =>
    set({
      nodeid: "",
      name: "",
      actor: "",
      prompt: "",
      provider: "",
      model: "",
      tool: null,
      nodeDialogOpen: false,
      nodeDialogMode: "create",
      toolOpen: false,
      providerOpen: false,
      modelOpen: false,
    }),

  flowEdges: [],
  setFlowEdges: (flowEdges) => set({ flowEdges }),
  nodePositions: {},
  setNodePositions: (nodePositions) => set({ nodePositions }),

  pendingEdgeInsert: null,
  setPendingEdgeInsert: (pendingEdgeInsert) => set({ pendingEdgeInsert }),

  updateHistory: (updater) => set((state) => ({ history: updater(state.history) })),
  updateSessionMessages: (updater) => set((state) => ({ history: updater(state.history) })),
}));
