import { create } from "zustand";
import type { GithubClientState } from "../types/type";

export const githubauthstore = create<GithubClientState>((set) => ({
  provider: "",
  model: "",
  sessionmessage: [],
  input: "",
  sending: false,
  loadingfetch: false,
  loadingerror: false,
  loadinggithubmsg: false,
  nextCursor: null,
  hasMore: false,
  loadingMore: false,
  type: "text",
  repoid: null,
  isChecking: false,
  pendingApproval: null,
  pendingApprovalRef: { current: null },
  threadIdRef: { current: null },
  lightboxImages: [],
  lightboxIndex: 0,
  lightboxOpen: false,
  copiedIndex: null,
  uploadingImages: false,
  uploadingImageUrls: new Set(),
  pendingImages: [],
  modelList: [],
  modelsLoading: false,
  reasoningLevel: "",

  setProvider: (v) => set({ provider: v, model: "" }),
  setModel: (v) => set({ model: v }),
  setsessionmessage: (v) => set({ sessionmessage: v }),
  setInput: (v) => set({ input: v }),
  setSending: (v) => set({ sending: v }),
  setloadingfetch: (v) => set({ loadingfetch: v }),
  setloadingerror: (v) => set({ loadingerror: v }),
  setloadinggithubmsg: (v) => set({ loadinggithubmsg: v }),
  setNextCursor: (v) => set({ nextCursor: v }),
  setHasMore: (v) => set({ hasMore: v }),
  setLoadingMore: (v) => set({ loadingMore: v }),
  settype: (v) => set({ type: v }),
  setrepoid: (v) => set({ repoid: v }),
  setIsChecking: (v) => set({ isChecking: v }),
  setPendingApproval: (v) => set({ pendingApproval: v }),
  setLightboxImages: (v) => set({ lightboxImages: v }),
  setLightboxIndex: (v) => set({ lightboxIndex: v }),
  setLightboxOpen: (v) => set({ lightboxOpen: v }),
  setCopiedIndex: (v) => set({ copiedIndex: v }),
  setUploadingImages: (v) => set({ uploadingImages: v }),
  setUploadingImageUrls: (v) => set({ uploadingImageUrls: v }),
  setPendingImages: (v) => set({ pendingImages: v }),
  setModelList: (v) => set({ modelList: v }),
  setModelsLoading: (v) => set({ modelsLoading: v }),
  setReasoningLevel: (v) => set({ reasoningLevel: v }),

  resetgithub: () => set({ provider: "", model: "" }),
  updateSessionMessages: (updater) =>
    set((state) => ({ sessionmessage: updater(state.sessionmessage) })),
}));
